apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metacontroller-framework
  name: metacontroller-framework
spec:
  selector:
    matchLabels:
      app: metacontroller-framework
  template:
    metadata:
      labels:
        app: metacontroller-framework
    spec:
      containers:
      - image: CONTAINER_IMAGE_PLACEHOLDER
        imagePullPolicy: Always
        name: metacontroller-framework
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metacontroller-framework
  name: metacontroller-framework
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: metacontroller-framework